steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/api-boilerplate:$BUILD_ID',
      '-f', 'docker/api/Dockerfile',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/api-boilerplate:$BUILD_ID']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'api-boilerplate'
      - '--image'
      - 'gcr.io/$PROJECT_ID/api-boilerplate:$BUILD_ID'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--port'
      - '1234'

images:
  - 'gcr.io/$PROJECT_ID/api-boilerplate:$BUILD_ID'
